"use strict";
const assert = require("assert"), path = require("path");
const mem = {};
global.localStorage = { getItem: k => mem[k] || null, setItem: (k, v) => { mem[k] = String(v); } };
const L = require("../gen/lernstand.js");
const S = require("../gen/sql.js"), D = require("../gen/sql-daten.js");
const A = require("../gen/algo.js");
const initSql = require("../vendor/sqljs-1.14.2/sql-wasm.js");
assert.strictEqual(typeof S.pruefen, "function", "produktiver Prüfknopf muss persistierbare Beobachtung auslösen");
assert.strictEqual(typeof A.schrittBewerten, "function", "Algorithmus-Prüfung muss echte Eingaben beurteilen und beobachten");
initSql({ locateFile: f => path.join(__dirname, "../vendor/sqljs-1.14.2", f) }).then(db => {
  S.setzeSQL(db);
  const sql = id => D.AUFGABEN.find(a => a.id === id);
  assert(S.pruefen(sql("g1"), "select ort, name, vorname from kunde").ok);
  assert(!S.pruefen(sql("g1"), "select Ort from Kunde").ok);
  S.hilfeMerken("g2", "hilfe");
  assert(S.pruefen(sql("g2"), sql("g2").loesung).ok);
  S.hilfeMerken("g3", "loesung");
  assert(S.pruefen(sql("g3"), sql("g3").loesung).ok);
  const ev = L.list().filter(e => e.source === "sql");
  assert.deepStrictEqual(ev.map(e => e.support), ["selbst", "hilfe", "hilfe", "loesung"]);
  assert.deepStrictEqual(ev.map(e => e.correct), [1, 0, 1, 1]);
  assert.strictEqual(ev[0].answers.code, "select ort, name, vorname from kunde");
  assert.strictEqual(L.summary().find(s => s.topic === "sql").independent, 1);
  assert.strictEqual(JSON.parse(mem["ap2:sql"]).a.g1.n, 2);

  const run = { modus: "bubble", feld: [5, 1, 4, 2], auf: true, k: 0, support: "selbst" };
  assert(A.schrittBewerten(run, [1, 4, 2, 5], [1, 4, 2, 5], "sortieren"));
  run.k = 1;
  assert(!A.schrittBewerten(run, [1, 4, 2, 5], [1, 2, 4, 5], "sortieren"));
  assert(A.schrittBewerten(run, [1, 2, 4, 5], [1, 2, 4, 5], "sortieren"));
  run.support = "loesung"; run.k = 2;
  A.schrittBewerten(run, [1, 2, 4, 5], [1, 2, 4, 5], "sortieren");
  const algo = L.list().filter(e => e.source === "algo");
  assert.deepStrictEqual(algo.map(e => e.support), ["selbst", "selbst", "hilfe", "loesung"]);
  assert.deepStrictEqual(algo[1].answers.input, [1, 4, 2, 5]);
  assert.strictEqual(algo[1].task, algo[2].task, "Korrektur bleibt dieselbe konkrete Teilaufgabe");
  assert.strictEqual(L.summary().find(s => s.topic === "algo").ratio, 0.5);
  const mitCode = { modus: "bubble", feld: [2, 1], k: 0 };
  A.hilfeNutzen(mitCode, "hilfe");
  A.schrittBewerten(mitCode, [1, 2], [1, 2], "sortieren");
  assert.strictEqual(L.list().slice(-1)[0].support, "hilfe", "Pseudocode aufdecken ist sichtbare Hilfe");
  console.log("lernstand integrations: echte SQL-Prüfung, Algorithmus-Eingaben, Hilfe und Korrekturen OK");
}).catch(e => { console.error(e); process.exitCode = 1; });
